### ISSUE TITLE
Add remirepo.net to Supported Repositories

### ISSUE THREAD

**Issue by futureweb** [vzlinux/vzdeploy#1]
Hey there,
thank you for your great work on those Scripts! :-)
As many Centos 7/8 Admins use the remirepo.net repositories for PHP would it be possible to add these to the supported repositories in the Centos -> VLinux migrations scripts?

Shouldn't normally cause any problems:
https://rpms.remirepo.net/enterprise/7/
https://rpms.remirepo.net/enterprise/8/

thx
Andy

**Comment by dsilakov** [comment]
Yes, why not.

**Comment by dsilakov** [comment]
Note that you should add corresponding remi-8 repos to the container template configs to be able to correctly upgrade remy packages via vzconvert.

**Comment by futureweb** [comment]
@dsilakov - thank you for your fast response on this and the Note regarding tpl config ... most likely I'm going to do first migration tests this or coming week with out Centos 8 Containers.

**Comment by futureweb** [comment]
@dsilakov - one further Question ... there are some Centos 8 Containers which are installed without Template. Can't they be migrated with the Script as we can't add the Repos to the Tpl Config?

![grafik](https://user-images.githubusercontent.com/1698881/152776979-e9b2e5ed-a06e-435a-9a5c-db7bb8c86415.png)

**Comment by dsilakov** [comment]
Worht to try, but you should then comment out check for supported template.

And probably it will be easier to launch vzdeploy8_ct against such CTs

**Comment by dsilakov** [comment]
vzdeploy should not report remi repos as unsupported anymore
